// <auto-generated />
using System;
using EStoreRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EStoreRepository.Migrations.TypeRepositoryMigrations
{
    [DbContext(typeof(TypeRepository))]
    [Migration("20260901042143_Types")]
    partial class Types
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstoreModel.Models.Types.TypeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("281b7b06-5f08-4f08-afb1-ce13f655df09"),
                            Name = "Fridge"
                        },
                        new
                        {
                            Id = new Guid("6e2f9ac5-b6e9-4708-b184-71dd0f2815af"),
                            Name = "Washing Machine"
                        },
                        new
                        {
                            Id = new Guid("eb95ffcd-d9b5-480b-a042-cb75d262ff69"),
                            Name = "Mobile"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
