// <auto-generated />
using System;
using EStoreRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EStoreRepository.Migrations
{
    [DbContext(typeof(BrandRepository))]
    [Migration("20260828042455_BrandRepostory")]
    partial class BrandRepostory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstoreModel.Models.Brands.BrandModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c462a1ab-29a5-49ef-9c4e-76a91524189c"),
                            Name = "Vivo"
                        },
                        new
                        {
                            Id = new Guid("5528b81d-519a-4ae7-8908-948e56ccc9ab"),
                            Name = "Reliance"
                        },
                        new
                        {
                            Id = new Guid("db8b6f07-faea-4176-81bd-496129970019"),
                            Name = "Samsung"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
